apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingintelligence
  name: pingintelligence
spec:
  ports:
  - name: pi-in
    port: 8443
  - name: pi-app
    port: 8010
  selector:
    role: pingintelligence
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingintelligence
  name: pingintelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingintelligence
  template:
    metadata:
      labels:
        role: pingintelligence
      name: pingintelligence
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
      - envFrom:
        - configMapRef:
            name: pingintelligence-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        image: pingidentity/pingintelligence:edge
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        name: pingintelligence
        ports:
        - containerPort: 8443
        - containerPort: 8010
        resources:
          limits:
            cpu: "1"
            memory: 1.5Gi
          requests:
            cpu: "1"
            memory: 1.5Gi