global:
  ingress:
    enabled: true
    #addReleaseNameToHost: "subdomain"
    addReleaseNameToHost: "prepend"
    defaultDomain: "ping-devops.com"
    defaultTlsSecret:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx-public"