# ping-devops-values.yaml
global:
  ingress:
    enabled: true
    addReleaseNameToHost: subdomain
    defaultDomain: ping-devops.com
    defaultTlsSecret:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx-public"

pingaccess-admin:
  enabled: false

pingaccess-engine:
  enabled: false

pingauthorize:
  enabled: false

pingdataconsole:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/aaronhaskins-ping/pingidentity-server-profiles
    SERVER_PROFILE_PATH: baseline/pingdataconsole

pingdirectory:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/aaronhaskins-ping/pingidentity-server-profiles
    SERVER_PROFILE_PATH: baseline/pingdirectory

pingfederate-admin:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/aaronhaskins-ping/pingidentity-server-profiles
    SERVER_PROFILE_PATH: baseline/pingfederate
    SERVER_PROFILE_BRANCH: statefulset-test
    SERVER_PROFILE_UPDATE: "true"
    PF_LOG_LEVEL: DEBUG
    IMAGE_VERSION: 11.3.1-alpine_3.18.3-al11-latest
  workload:
    type: StatefulSet

pingfederate-engine:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/aaronhaskins-ping/pingidentity-server-profiles
    SERVER_PROFILE_PATH: baseline/pingfederate
    SERVER_PROFILE_BRANCH: statefulset-test
    SERVER_PROFILE_UPDATE: "true"
    PF_LOG_LEVEL: DEBUG
    IMAGE_VERSION: 11.3.1-alpine_3.18.3-al11-latest

pingcentral:
  enabled: false
